server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: sdfsdf

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.springbootdemo.entity
